### ISSUE TITLE
Add missing OAuth Scopes for Write Access

### ISSUE THREAD

**Issue by camposer** [strongdm/accessbot#89]
**Describe the bug**
The current [slack-manifest.yaml](../blob/main/slack-manifest.yaml) configuration is missing the OAuth Scopes for Writing, please add them.

Here's the file you can use for reference:
```
_metadata:
  major_version: 1
  minor_version: 1
display_information:
  name: accessbotDavid
  description: AccessBot using Bolt
  background_color: "#2c2d30"
features:
  app_home:
    home_tab_enabled: false
    messages_tab_enabled: true
    messages_tab_read_only_enabled: false
  bot_user:
    display_name: accessbot_bolt
    always_online: false
oauth_config:
  scopes:
    bot:
      - channels:history
      - channels:read
      - chat:write
      - groups:history
      - groups:write
      - im:history
      - im:write
      - incoming-webhook
      - mpim:write
      - reactions:write
      - users:read
      - users:read.email
      - groups:read
settings:
  event_subscriptions:
    bot_events:
      - message.channels
      - message.groups
      - message.im
  interactivity:
    is_enabled: true
  org_deploy_enabled: false
  socket_mode_enabled: true
  token_rotation_enabled: false
```
